SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

IF OBJECT_ID('hst_ERPRecipes') IS NOT NULL DROP TABLE [dbo].[hst_ERPRecipes]
GO

CREATE TABLE [dbo].[hst_ERPRecipes](
    [ID] [int] IDENTITY(1,1) NOT NULL,
    [RecipeGUID] [uniqueidentifier] NOT NULL,
    [isSendErp] [bit] NOT NULL DEFAULT ((1)),
    [Date_send] [datetime] NOT NULL DEFAULT (Getdate()),
    PRIMARY KEY CLUSTERED
(
[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY]
    GO
    SET ANSI_PADDING ON
    GO